import tg from '../../images/image_telegram.svg'
import vk from '../../images/image_vk.svg'
import ig from '../../images/image_instagram.svg'
import wa from '../../images/image_whatsapp.svg'
import polygon from '../../images/Polygon.svg'
import like from '../../images/like.svg'
import basket from '../../images/basket.svg'
import burgerlogo from '../../images/burger__logo.svg'
import burgervector from '../../images/burger__vector.svg'
import mainlogo from '../../images/logo.svg'
import headervector from '../../images/header__vector.svg'
import arrow from '../../images/arrow.svg'
import trash from '../../images/trash.svg'
import tgC from '../../images/contacts__tg.svg'
import vkC from '../../images/contacts_vk.svg'
import igC from '../../images/contacts__ig.svg'
import waC from '../../images/contacts__wa.svg'

export { tg, vk, ig, wa, polygon, like, basket, burgerlogo, burgervector, mainlogo, headervector, arrow, trash, tgC, vkC, igC, waC, }